services:
  jekyll:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "35735:35735"  # For LiveReload
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 5000 --livereload --livereload-port 35735
